# Generated by Django 3.2.9 on 2021-11-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('land_link', models.CharField(max_length=100)),
                ('kyc', models.CharField(choices=[('Pan', 'Pan'), ('Aadhar', 'Aadhar'), ('Gst', 'Gst')], max_length=50)),
                ('accountNumber', models.CharField(max_length=100)),
                ('bankName', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('accountName', models.CharField(max_length=50)),
                ('timing', models.DateTimeField(auto_now_add=True)),
                ('about', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='Logo/')),
            ],
        ),
    ]
