# Generated by Django 3.2.9 on 2021-11-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='kyc',
        ),
        migrations.AddField(
            model_name='vendor',
            name='PanImage',
            field=models.ImageField(default=1, upload_to='Pan/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='aadharImage',
            field=models.ImageField(default=1, upload_to='Aadhar/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='gstImage',
            field=models.ImageField(default=1, upload_to='gst'),
            preserve_default=False,
        ),
    ]
