# Generated by Django 3.2.9 on 2021-11-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0002_auto_20211109_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='land_link',
            new_name='land_line',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='PanImage',
            new_name='panImage',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gstImage',
            field=models.ImageField(upload_to='gst/'),
        ),
    ]
