# Generated by Django 3.2.9 on 2021-11-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0003_auto_20211109_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='otherservice',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
